global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: ["traefik:8082"]

  - job_name: orchestrator
    static_configs:
      - targets: ["orchestrator:8000"]

  - job_name: sample-app
    metrics_path: /metrics/
    static_configs:
      - targets: ["nexus-app-sample-app:8000"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
